version: '3.8'

volumes:
  mysql-data:  

services:
  coffeebean-db:
    container_name: coffeebean-db
    image: mysql:8.0
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    restart: always

  backend:
    container_name: coffeebean-backend
    build: ./
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://coffeebean-db:3306/${DB_NAME}?allowPublicKeyRetrieval=true   
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - '127.0.0.1:8083:8083'
    depends_on:
      - coffeebean-db
    restart: always

